const productsMock = [{ "id": 1, "image": "http://dummyimage.com/233x224.bmp/cc0000/ffffff", "title": "Wine - Magnotta - Bel Paese White", "price": 86, "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst." },
{ "id": 2, "image": "http://dummyimage.com/234x126.bmp/dddddd/000000", "title": "Walkers Special Old Whiskey", "price": 15, "description": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero." },
{ "id": 3, "image": "http://dummyimage.com/179x148.png/cc0000/ffffff", "title": "Juice - Propel Sport", "price": 11, "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus." },
{ "id": 4, "image": "http://dummyimage.com/151x171.jpg/dddddd/000000", "title": "Cheese - Camembert", "price": 99, "description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh." },
{ "id": 5, "image": "http://dummyimage.com/228x124.bmp/ff4444/ffffff", "title": "Tea - Vanilla Chai", "price": 72, "description": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus." },
{ "id": 6, "image": "http://dummyimage.com/133x219.jpg/ff4444/ffffff", "title": "Potatoes - Purple, Organic", "price": 17, "description": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi." },
{ "id": 7, "image": "http://dummyimage.com/239x193.bmp/dddddd/000000", "title": "Beef - Striploin Aa", "price": 42, "description": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque." },
{ "id": 8, "image": "http://dummyimage.com/237x104.jpg/cc0000/ffffff", "title": "Longos - Grilled Salmon With Bbq", "price": 32, "description": "Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi." },
{ "id": 9, "image": "http://dummyimage.com/196x125.png/cc0000/ffffff", "title": "Iced Tea Concentrate", "price": 33, "description": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque." },
{ "id": 10, "image": "http://dummyimage.com/144x141.png/5fa2dd/ffffff", "title": "Sauce - Apple, Unsweetened", "price": 3, "description": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus." }];

module.exports = {
  productsMock
};